---
# tasks file for apache
    - name: "Install Apache"
      package: name=httpd state=present
    - name: "Copy File"
      copy: src=files/index.html dest=/var/www/html/index.html
    - name: "Starting Apache"
      service: name=httpd state=started
